[app_servers]
#Jakub Dykier 236641
app_node_1 ansible_host=20.43.61.79 ansible_user=adminuser

[db_servers]
db_node_1 ansible_host=51.103.25.213 ansible_user=adminuser

[all:vars]
ansible_password="Trudne!H@slo123"
ansible_connection=ssh
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
