#Jakub Dykier 236641
- name: First automation - system update
  hosts: all
  become: yes

  tasks:
    - name: Step 1 - Refresh the list of available packages (equivalent of apt update)
      apt:
        update_cache: yes

    - name: Step 2 - Install the latest versions of software (equivalent of apt upgrade)
      apt:
        upgrade: yes
